### ISSUE TITLE
Card not loading

### ISSUE THREAD

**Issue by juuurc** [enriqg9/dual-thermostat#15]
Hello,
I've seen someone already opened an issue regarding the card not beeing loaded with issue custom:dual-thermostat does not exist but it hasn't been solved.

My HASS version is: 0.96.5

And here is the yaml as I used it:
 ```
       - type: custom:dual-thermostat
          name: Bedroom
          entities:
            - entity: climate.bedroom_aircon
              type: cool
            - entity: climate.bedroom_heat
              type: heat
          fan_control: true
```

Thanks for help, 
Jure
