### ISSUE TITLE
dual thermostat card problem on 0.99.3 Hassio 

### ISSUE THREAD

**Issue by mike829** [enriqg9/dual-thermostat#19]
Hello Everybody,

I installed the plugin from HACS.

I added on Loveleace config:
```
resources:
   - url: /community_plugin/dual-thermostat/dual-thermostat.js
     type: js
```

I already have setup in my configuration.yaml the n.2 thermostat:

```
climate:          
  - platform: generic_thermostat
    name: termostato_heat
    heater: switch.shelly_shsw_1_ba31bb
    target_sensor: sensor.cpu_temp
    min_temp: 15
    max_temp: 70
    ac_mode: false
    target_temp: 20
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "off"
    away_temp: 16
    precision: 0.1
    
         
  - platform: generic_thermostat
    name: termostato_cool
    heater: switch.shelly_shsw_1_ba31bb
    target_sensor: sensor.cpu_temp
    min_temp: 15
    max_temp: 70
    ac_mode: true
    target_temp: 20
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "off"
    away_temp: 16
    precision: 0.1    

```
When I add the following manual card:

```

type: 'custom:dual-thermostat'
name: General
entities:
      - entity: climate.termostato_cool
        type: cool
      - entity: climate.termostato_heat
        type: heat
fan_control: false
min_slider: 60
max_slider: 80
```
I am not able to see the card, if fan is true everything on lovelace disapperas... Do you have some suggestion?
