### ISSUE TITLE
Controls Not Displaying

### ISSUE THREAD

**Issue by northrup** [enriqg9/dual-thermostat#23]
Here's what I'm seeing in the Lovelace UI:
![image](https://user-images.githubusercontent.com/11050/68535922-aa9c8a80-030f-11ea-9dd4-9d17c48822db.png)

and here's the code that I have:

```
      - type: custom:dual-thermostat
        name: 1st Floor
        entities:
          - entity: climate.honeywell_t6_1_cooling
            type: cool
          - entity: climate.honeywell_t6_1_heating
            type: heat
        #fan_control: true
```

If I enable `fan_control` the entire thermostat object disappears from the Lovelace UI.

I'm running Home Assistant 0.101.3 and the latest version of the `dual-thermostat` code that is in the `dst` folder.
