### ISSUE TITLE
Help with CSS for background transparency

### ISSUE THREAD

**Issue by backcountrymountains** [enriqg9/dual-thermostat#26]
This card has been great for controlling my z-wave thermostat, which, for whatever reason, reports as two thermostats. Thanks for making it.

I got some neat-o theme from somewhere that uses transparency but the inner part of the thermostat circle doesn't seem to follow the style of the rest of the card. I have no knowledge of CSS so I'm uploading a file that shows the issue. I'm hoping you can help me fix it.

Thanks.
![dual thermostat](https://user-images.githubusercontent.com/29560911/69997736-070b5800-1512-11ea-9c8d-97c1a5816a8b.PNG)

**Comment by enriqg9** [comment]
```css
```

**Comment by enriqg9** [comment]
Below is the property that controls the round slider inner block. However, roundslider uses this block to cover content, if you set it to transparent it will reveal the full circle.

```css
      #thermostat .rs-inner.rs-bg-color.rs-border,
        #thermostat .rs-overlay.rs-transition.rs-bg-color {
          background-color: var(--paper-card-background-color, white);
        }
```

![Screen Shot 2019-12-03 at 10 03 42 PM](https://user-images.githubusercontent.com/5072570/70111740-ce09db00-1618-11ea-9f82-03e90a924e1f.png)
