### ISSUE TITLE
No longer rendering in Lovelace in 0.110.1 inside Vertical Stack 

### ISSUE THREAD

**Issue by Linwood-F** [enriqg9/dual-thermostat#32]
Been using this for a long time, and upgraded to 0.110.1 and it now renders briefly and disappears as the lovelace page appears (windows 10, Chrome, Firefox).  Edge does work, interestingly.  This seems to occur only (so far at least) when inside vertical-stack.

When I look in debug it is rendered as an empty item with zero height (see screen shot). 

![zero-height](https://user-images.githubusercontent.com/13143855/82758789-b08f2000-9db6-11ea-8a67-ae5ae589ef95.jpg)

Debug console in firefox shows an error of "this.stateObj is null" at line 221:1115 but that's perhaps because it's not present in the resulting hierarchy. 

Here is an example where I put it on its own page.   I suppose this could be a failure in vertical stack but that's so widely used and I see no reports otherwise.

```
  - title: Test 
    path: test
    panel: false
    cards: 
      - type: vertical-stack
        cards:
          - type: "custom:dual-thermostat"
            entities:
              - entity: climate.thermostat
                type: cool
              - entity: climate.thermostat
                type: heat
            fan_control: true
            name: HVAC
            min_slider: 60
            max_slider: 85
```
