### ISSUE TITLE
Support for dual climate entites.

### ISSUE THREAD

**Issue by CRCinAU** [enriqg9/dual-thermostat#5]
As per: https://community.home-assistant.io/t/dual-thermostat-card/85798/86?u=crcinau

I currently have 2 x separate climate entities. One controls an A/C via IR, the other is a heater via dry contacts.

My config is as follows:
```
entities:
  - entity: climate.aircon
    type: cool
  - entity: climate.heater
    type: heat
fan_control: false
max_slider: 30
min_slider: 15
name: Climate Control
type: 'custom:dual-thermostat'
```

You mentioned: 
> Not with the current card but that should be an easy fix, just loop on each entity and push each mode to an array. I’ll look at it whenever I get a chance.

Starting this github issues to try and track this.
